### ISSUE TITLE
public class CashRegister

### ISSUE THREAD

**Issue by kojoericfrimpong76** [kwurst/gitlab-course-managment-scripts#3]
public class Cash Register
{
Item Count++;
private static final Item count(Cash Register<target)
Cash Register=Cash + price
}
...

**Comment by kojoericfrimpong76** [comment]
public class Balance(Balance<target Balance)
{
year++;
double+ Interest Balance(Balance<target)
balance=balance+ Interest 
}
...

**Comment by kwurst** [comment]
Your comments and issue have nothing to do with this repository.

**Comment by kojoericfrimpong76** [comment]
While (balance<target Investment)
{
year++;
double +Interest balance(balance<target)
balance=balance+ Interest
}
....
